/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRecipe: typeof import('./components/AddRecipe.vue')['default']
    DurationInput: typeof import('./components/Form/DurationInput.vue')['default']
    IngredientInput: typeof import('./components/Form/IngredientInput.vue')['default']
    RecipeImage: typeof import('./components/Recipe/RecipeImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
